<a href="https://www.kaggle.com/code/s1155077325/yoga-asana-recommender-system?scriptVersionId=126431847" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
#Import the libraries
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
#Load the data
data = pd.read_csv('/kaggle/input/yoga-asanas-and-its-benefits/final_asan1_1.csv')
data.head(5)

AID               AName                                        Description  \
0    1     Padanguli Naman  Sit in the base position with the legs outstre...   
1    2         Goolf Naman  Remain in the base position.\nSlowly move both...   
2    3        Goolf Chakra  Remain in the base position.\nKeep the legs sh...   
3    4       Goolf Ghooman  Remain in the base position.\nBend the right k...   
4    5  Janufalak Akarshan  Stay in the base position.\nGently contract th...   

                                            Benefits Contraindications  \
0  This group of asanas is concerned with looseni...               NaN   
1  This group of asanas is concerned with looseni...               NaN   
2  This group of asanas is concerned with looseni...               NaN   
3  All the foot and calf asanas help in returning...               NaN   
4  This group of asanas is concerned with looseni...               NaN   

                                           Breathing  \
0  Inhale as the toes move backward.\nExhale as t...   
1  Inhale as the feet move backward.\nExhale as t...   
2  Inhale on the upward movement.\nExhale on the ...   
3  Inhale on the upward movement.\nExhale on the ...   
4  Inhale while contracting.\nExhale while relaxi...   

                                           awareness  You tube Vdo link  \
0  On the stretching produced by the movement and...                NaN   
1  On the stretch in the foot, ankle, calf and le...                NaN   
2       On the rotation of the ankle and the breath.                NaN   
3                    On the rotation and the breath.                NaN   
4                 On the contraction and the breath.                NaN   

   Photo  References Variations      Level  
0    NaN         NaN        NaN  Beginners  
1    NaN         NaN        NaN  Beginners  
2    NaN         NaN        NaN  Beginners  
3    NaN         NaN        NaN  Beginners  
4    NaN         NaN        NaN  Beginners

In [3]:
#the summary of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   AID                226 non-null    int64  
 1   AName              226 non-null    object 
 2   Description        225 non-null    object 
 3   Benefits           215 non-null    object 
 4   Contraindications  158 non-null    object 
 5   Breathing          188 non-null    object 
 6   awareness          186 non-null    object 
 7   You tube Vdo link  0 non-null      float64
 8   Photo              0 non-null      float64
 9   References         0 non-null      float64
 10  Variations         51 non-null     object 
 11  Level              177 non-null    object 
dtypes: float64(3), int64(1), object(8)
memory usage: 21.3+ KB


In [4]:
#Create a list that wants to keep
columns = ['AName','Description','Benefits']

In [5]:
#Create a function to combine the important columns/features
def combine_features(data):
    features =[]
    for i in range(0,data.shape[0]):
        features.append(str(data['AName'][i]) + ' '+str(data['Description'][i])+ ' '+str(data['Benefits'][i]))
        
    return features

In [6]:
# Create a column to store the combine features
data['combine_features']= combine_features(data)
#Show the data
data.head(5)

AID               AName                                        Description  \
0    1     Padanguli Naman  Sit in the base position with the legs outstre...   
1    2         Goolf Naman  Remain in the base position.\nSlowly move both...   
2    3        Goolf Chakra  Remain in the base position.\nKeep the legs sh...   
3    4       Goolf Ghooman  Remain in the base position.\nBend the right k...   
4    5  Janufalak Akarshan  Stay in the base position.\nGently contract th...   

                                            Benefits Contraindications  \
0  This group of asanas is concerned with looseni...               NaN   
1  This group of asanas is concerned with looseni...               NaN   
2  This group of asanas is concerned with looseni...               NaN   
3  All the foot and calf asanas help in returning...               NaN   
4  This group of asanas is concerned with looseni...               NaN   

                                           Breathing  \
0  Inhale as the toes move backward.\nExhale as t...   
1  Inhale as the feet move backward.\nExhale as t...   
2  Inhale on the upward movement.\nExhale on the ...   
3  Inhale on the upward movement.\nExhale on the ...   
4  Inhale while contracting.\nExhale while relaxi...   

                                           awareness  You tube Vdo link  \
0  On the stretching produced by the movement and...                NaN   
1  On the stretch in the foot, ankle, calf and le...                NaN   
2       On the rotation of the ankle and the breath.                NaN   
3                    On the rotation and the breath.                NaN   
4                 On the contraction and the breath.                NaN   

   Photo  References Variations      Level  \
0    NaN         NaN        NaN  Beginners   
1    NaN         NaN        NaN  Beginners   
2    NaN         NaN        NaN  Beginners   
3    NaN         NaN        NaN  Beginners   
4    NaN         NaN        NaN  Beginners   

                                    combine_features  
0  Padanguli Naman Sit in the base position with ...  
1  Goolf Naman Remain in the base position.\nSlow...  
2  Goolf Chakra Remain in the base position.\nKee...  
3  Goolf Ghooman Remain in the base position.\nBe...  
4  Janufalak Akarshan Stay in the base position.\...

In [7]:
#Convert the text from combine_features to a matrix of word counts
cm =CountVectorizer().fit_transform(data['combine_features'])

In [8]:
#Get the cosine similarity matrix from the word matrix
cs = cosine_similarity(cm)
#Print the scores
print(cs)

[[1.         0.89039041 0.84081994 ... 0.79765929 0.79714428 0.78220027]
 [0.89039041 1.         0.79780783 ... 0.68259551 0.66540925 0.65936911]
 [0.84081994 0.79780783 1.         ... 0.74322624 0.75372894 0.71650641]
 ...
 [0.79765929 0.68259551 0.74322624 ... 1.         0.83392692 0.7958211 ]
 [0.79714428 0.66540925 0.75372894 ... 0.83392692 1.         0.87464141]
 [0.78220027 0.65936911 0.71650641 ... 0.7958211  0.87464141 1.        ]]


In [9]:
#Get the Asana Name that Yogi likes
Asana = data['AName'][100]
#Show the title
Asana

'Ardha Shalabhasana (half locust pose)'

In [10]:
#Find the Asana ID that the Yogi likes
Asana_ID =data[data.AName==Asana]['AID'].values[0]
Asana_ID

101

In [11]:
#Create a list of tuples in the form(AID, similarity)
scores = list(enumerate(cs[Asana_ID]))

In [12]:
#Sort the list of similar Asanas in descending order
sorted_scores = sorted (scores, key = lambda x:x[1], reverse = True)
#Show the sorted scores
sorted_scores = sorted_scores[1:]
sorted_scores

[(102, 0.9429527734285548),
 (104, 0.9337158742742672),
 (103, 0.9336603672426861),
 (162, 0.9333597729660397),
 (125, 0.9301516281303309),
 (92, 0.9270957356693698),
 (167, 0.9251543860997608),
 (129, 0.9237571000546371),
 (134, 0.923365543844297),
 (161, 0.9229259843930051),
 (182, 0.9226480317709319),
 (124, 0.9210902050339415),
 (133, 0.9210174438361299),
 (98, 0.9205846177468984),
 (173, 0.9195683161915835),
 (171, 0.9195024302178646),
 (169, 0.9194429853557483),
 (105, 0.9194072539702499),
 (109, 0.918213661795905),
 (99, 0.9166022529463523),
 (185, 0.9137484289019694),
 (106, 0.9137251359665869),
 (68, 0.9121581133581869),
 (211, 0.9120312547375872),
 (111, 0.910349716228205),
 (147, 0.909090529187594),
 (178, 0.908720568655403),
 (165, 0.9073949168977385),
 (160, 0.9073502698566066),
 (117, 0.9072201162611119),
 (135, 0.9069046593349337),
 (128, 0.9068900306787812),
 (172, 0.9067837764688507),
 (126, 0.9065318584461617),
 (148, 0.9056424201819442),
 (97, 0.905635807150732),
 (1

In [13]:
#Create a loop to print the first 5 Asanas from the sorted list
j = 0
print('The 5 most recommended asanas to '+Asana+' are:\n')
for item in sorted_scores:
    Asana_Name = data.loc[data['AID'] == item[0]]['AName']
    Level = data.loc[data['AID'] == item[0]]['Level']
    Asana_ben = data.loc[data['AID'] == item[0]]['Benefits']
    print(j+1,*Asana_Name,*Level,*Asana_ben,sep='\n')
    j=j+1
    if j >=6:
            break 

The 5 most recommended asanas to Ardha Shalabhasana (half locust pose) are:

1
Shalabhasana (locust pose)
Intermediate
Shalabhasana strengthens the lower back and
pelvic organs, and provides relief from backache, mild
sciatica and slipped disc as long as the condition is not
serious. It tones and balances the functioning of the
liver, stomach, bowels and other abdominal organs,
and stimulates the appetite. It tightens the muscles of
the buttocks and causes the body to do vajroli mudra
spontaneously.
2
Dhanurasana (bow pose)
Intermediate
The entire alimentary canal is reconditioned by this

asana. The liver, abdominal organs and muscles are massag-
ed. The pancreas and adrenal glands are toned, balancing

their secretions. The kidneys are massaged and excess
weight is reduced around the abdominal area.
This leads to improved functioning of the digestive,
excretory and reproductive organs and helps to remove
gastrointestinal disorders, dyspepsia, chronic constipation
and sluggishness of 